#pragma once
#include <cstdint>

namespace TeaPacket::Input
{
    /// @brief Represents a button on a controller.
    /// @details Buttons are any boolean/digital values on a controller (pressed or unpressed only). <br>
    /// Each value in this enum is prefixed with a name.
    /// - START_ and END_ should never be polled. They are utility enum values.
    /// - KEY_ represents keys on a keyboard.
    /// - MOUSE_ represents mouse buttons.
    /// - PAD_ represents gamepad buttons.
    enum class InputButtonType : uint32_t{
        NONE = 0,
        START_KEY,
        KEY_BACKTICK,
        KEY_1,
        KEY_2,
        KEY_3,
        KEY_4,
        KEY_5,
        KEY_6,
        KEY_7,
        KEY_8,
        KEY_9,
        KEY_0,
        KEY_MINUS,
        KEY_EQUALS,
        KEY_BACKSPACE,
        KEY_TAB,
        KEY_Q,
        KEY_W,
        KEY_E,
        KEY_R,
        KEY_T,
        KEY_Y,
        KEY_U,
        KEY_I,
        KEY_O,
        KEY_P,
        KEY_LEFT_SQUARE_BRACKET,
        KEY_RIGHT_SQUARE_BRACKET,
        KEY_BACKSLASH,
        KEY_A,
        KEY_S,
        KEY_D,
        KEY_F,
        KEY_G,
        KEY_H,
        KEY_J,
        KEY_K,
        KEY_L,
        KEY_SEMICOLON,
        KEY_APOSTROPHE,
        KEY_ENTER,
        KEY_LEFT_SHIFT,
        KEY_Z,
        KEY_X,
        KEY_C,
        KEY_V,
        KEY_B,
        KEY_N,
        KEY_M,
        KEY_COMMA,
        KEY_PERIOD,
        KEY_FORWARD_SLASH,
        KEY_RIGHT_SHIFT,
        KEY_LEFT_CTRL,
        KEY_WIN,
        KEY_LEFT_ALT,
        KEY_SPACE,
        KEY_RIGHT_ALT,
        KEY_RIGHT_CTRL,
        KEY_ARROW_UP,
        KEY_ARROW_RIGHT,
        KEY_ARROW_DOWN,
        KEY_ARROW_LEFT,
        END_KEY = 0xFFFFFF,
        START_MOUSE,
        MOUSE_LEFT,
        MOUSE_RIGHT,
        MOUSE_MIDDLE,
        END_MOUSE,
        START_PAD,
        PAD_A,
        PAD_B,
        PAD_C,
        PAD_X,
        PAD_Y,
        PAD_Z,
        PAD_LEFT_BUMPER,
        PAD_RIGHT_BUMPER,
        PAD_LEFT_TRIGGER,
        PAD_RIGHT_TRIGGER,
        PAD_START,
        PAD_SELECT,
        PAD_DPAD_UP,
        PAD_DPAD_RIGHT,
        PAD_DPAD_DOWN,
        PAD_DPAD_LEFT,
        PAD_STICK_LEFT,
        PAD_STICK_RIGHT,
        END_PAD,
        START_MISC,
        MISC_TOUCH,
        END_MISC,
    };
}
